/*
    description: Speaker class
           -class contains the main TTS engine
           
    date created: -14/10/15

    log:-
    * No Updates Done*

     Listed Public Methods:
           * NONE*

*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Speech.Recognition;
using System.Speech.Synthesis;
using System.Threading;
using System.Windows;

namespace Project_Voix
{
     static class Speaker
     {
        static SpeechSynthesizer mainSynthesizer;

        //static constructor of the Class, which initialises the SpeechSynthesizer , and registers the several events
        static Speaker()                                            
        {
            mainSynthesizer=new SpeechSynthesizer();
            mainSynthesizer.SelectVoiceByHints(DataStore.CurrentUser.SynthesizerVoiceGender);
            mainSynthesizer.SetOutputToDefaultAudioDevice();

            DataStore.VoiceGenderChanged += DataStore_VoiceGenderChanged;                       //DataStore's VoiceGenderChanged event which occurs when the gender of the TTS engine has changed
            MainWindow.VolumeChanged += MainWindow_VolumeChanged;                               //MainWindow VolumeChanged event which occurs when Volume of the TTS engine changes
            MainWindow.RateChanged += MainWindow_RateChanged;                                   //MainWindow RateChanged event which occurs when Synthesis Rate of the TTS engine changes
            //mainSynthesizer.SpeakStarted += MainSynthesizer_SpeakStarted;
            //mainSynthesizer.SpeakCompleted += MainSynthesizer_SpeakCompleted;
        }

        private static void MainSynthesizer_SpeakCompleted(object sender, SpeakCompletedEventArgs e)
        {
            Init.ResumeRecog();
        }

        private static void MainSynthesizer_SpeakStarted(object sender, SpeakStartedEventArgs e)
        {
            Init.PauseRecog();
        }


        #region Private Methods

        private static void DataStore_VoiceGenderChanged(VoiceGender voiceGender)
        {
            //handler for the VoiceGenderChanged Event
            mainSynthesizer.SelectVoiceByHints(voiceGender);
        }

        private static void MainWindow_RateChanged(int rate)
        {
            //handler for the RateChanged event
            mainSynthesizer.Rate = rate;
        }


        private static void MainWindow_VolumeChanged(int vol)
        {
            //Handler for the VolumeChanged event
            mainSynthesizer.Volume = vol;
        }
        #endregion

        #region Public Methods
        public static void Synthesizer(object resp)
        {
            /*
                all the calls made by the ResponseGenerator SendForSynthesis 
                method are delegated to this method
            */
            DataStore.AddToMessageDump(string.Format("Synthesizer Method on thread : {0}", Thread.CurrentThread.ManagedThreadId));
            string response = null;
            try
            {
                response = resp as string;
            }
            catch (NullReferenceException e)
            {
                DataStore.AddToErrorLog(string.Format("Message : {0}\n Generated by {1}",e.Message,e.Source));
            }
            catch (Exception e)
            {
                DataStore.AddToErrorLog(string.Format("Message : {0}\n Generated by {1}", e.Message, e.Source));
                //MessageBox.Show(e.Message);
            }
            mainSynthesizer.SpeakAsync(response);
        }
        #endregion

    }
}
